# Generated by Django 4.1.7 on 2023-02-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesantiago', '0003_m_company_remove_m_extra_payment_m_extra_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_extra',
            name='api_id',
        ),
        migrations.AddField(
            model_name='m_extra',
            name='api_uid',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
