# Generated by Django 4.1.7 on 2023-02-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesantiago', '0006_alter_m_extra_payments_alter_m_network_companys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_extra',
            name='payments',
            field=models.ManyToManyField(default=[], related_name='extra_payments', to='bikesantiago.m_payment'),
        ),
        migrations.AlterField(
            model_name='m_network',
            name='companys',
            field=models.ManyToManyField(default=[], related_name='network_companys', to='bikesantiago.m_company'),
        ),
        migrations.AlterField(
            model_name='m_network',
            name='stations',
            field=models.ManyToManyField(default=[], related_name='network_stations', to='bikesantiago.m_station'),
        ),
    ]
