# Generated by Django 4.1.7 on 2023-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesantiago', '0007_alter_m_extra_payments_alter_m_network_companys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_extra',
            name='api_uid',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='m_network',
            name='api_id',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='m_station',
            name='api_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
