# Generated by Django 4.1.7 on 2023-02-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_project',
            name='name',
            field=models.CharField(max_length=2000, null=True, unique=True),
        ),
    ]
