# Generated by Django 4.1.7 on 2023-02-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seia', '0003_alter_m_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_project',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='m_project',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
